In [2]:
import numpy as np

In [3]:
x =np.array([[1,2,4],[1,3,3]],dtype=np.float64)
y = np.array([[1,4,4],[1,2,3]])
a = np.array([1,2,5])


In [4]:
np.shape(x)

(2, 3)

In [5]:
np.ndim(x)

2

In [6]:
x.nbytes

48

In [7]:
x[1,2]

3.0

In [8]:
x[0,:]

array([1., 2., 4.])

In [9]:
x[:,1]

array([2., 3.])

In [20]:
x[0,0::2]=4
x

array([[4., 2., 4.],
       [1., 3., 3.]])

In [31]:
a = np.array([
    [
        [1,2,3],[4,5,6],[7,8,9]
    ]
    ])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [44]:
a[:,1,:]

array([[7, 8, 9]])

In [52]:
np.zeros((1,2),dtype=np.int32)

array([[0, 0]])

In [56]:
z= np.full((3,2),fill_value=12,dtype=np.float32)
z

array([[12., 12.],
       [12., 12.],
       [12., 12.]], dtype=float32)

In [59]:
z=np.full_like(z,44)
z

array([[44., 44.],
       [44., 44.],
       [44., 44.]], dtype=float32)

In [62]:
np.random.rand(3,2)

array([[0.58832971, 0.50916414],
       [0.85192046, 0.71429748],
       [0.07906067, 0.04164157]])

In [63]:
np.random.random_sample(a.shape)

array([[[0.17232428, 0.84960524, 0.50823412],
        [0.44739582, 0.53466228, 0.30613003],
        [0.63000863, 0.34024449, 0.05769697]]])

In [71]:
np.random.randint(4,7,size=(3,4))

array([[6, 4, 6, 5],
       [6, 4, 6, 5],
       [6, 4, 6, 6]])

In [72]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [81]:
temp = np.array([[1,2,3],[3,4,5],[6,5,3]])
r = np.repeat(temp,3,axis=1)
r

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [3, 3, 3, 4, 4, 4, 5, 5, 5],
       [6, 6, 6, 5, 5, 5, 3, 3, 3]])

In [122]:
output = np.ones((5,5),dtype=int)
zs = np.zeros((3,3),dtype=int)
output[1:-1,1:-1] =zs
output[2,2]=9
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

**Mathematics**

In [123]:
x = np.array([1,2,3,4])

In [124]:
x-2

array([-1,  0,  1,  2])

In [125]:
x*4

array([ 4,  8, 12, 16])

In [126]:
x/2

array([0.5, 1. , 1.5, 2. ])

In [127]:
temp = np.array([6,5,4,3])
temp*x

array([ 6, 10, 12, 12])

In [128]:
temp-x

array([ 5,  3,  1, -1])

In [129]:
x**2

array([ 1,  4,  9, 16])

In [130]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**Linear Algebra**


In [137]:
a = np.ones((3,3))
b= np.full((3,2),fill_value=34)
a,b

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[34, 34],
        [34, 34],
        [34, 34]]))

In [140]:
np.matmul(a,b)

array([[102., 102.],
       [102., 102.],
       [102., 102.]])

In [141]:
i = np.identity(3)
np.linalg.det(i)

1.0

In [144]:
a = np.array([[1,2,3],[4,5,6],[22,33,44]])
b = np.array([[4,32,12],[4,21,22],[41,11,22]])
a,b


(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [22, 33, 44]]),
 array([[ 4, 32, 12],
        [ 4, 21, 22],
        [41, 11, 22]]))

**Stats**

In [147]:
np.sum(a)

120

In [148]:
np.max(a,axis=1)

array([ 3,  6, 44])

**Reshaping**


In [152]:
a = np.array([[1,2,3],[4,5,7],[51,22,33]])
np.reshape(a,(1,9))

array([[ 1,  2,  3,  4,  5,  7, 51, 22, 33]])

In [156]:
a=np.array([3,4,5,6])
b = np.array([1,2,3,4])
np.vstack([a,b,a,b])
np.hstack([a,b,a])

array([3, 4, 5, 6, 1, 2, 3, 4, 3, 4, 5, 6])

In [160]:
a>4

array([False, False,  True,  True])

In [191]:
a = np.random.randint(53,size=(5,5))
print(a)
a[[0,1,4],3:]

[[41 21 14 27 39]
 [42 28  7 50 41]
 [ 5  9 29  4  4]
 [46 11 41 24 10]
 [26 42  4 30 38]]


array([[27, 39],
       [50, 41],
       [30, 38]])